name: dreamwalk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - gensim=4.2.0
  - networkx=2.8.8
  - pandas=1.4.4
  - scikit-learn=1.1.3
  - scipy=1.9.1
  - numpy=1.23.3
  - tqdm=4.64.1
  - parmap=1.6.0
